apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: conference-ingress 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: conference-ui.192.168.99.101.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: ui 
          servicePort: 8080
      - path: /callback
        backend:
          serviceName: ui 
          servicePort: 8080
  - host: conference-api.192.168.99.101.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: apollo 
          servicePort: 4000
