acceptLicenseAgreement: "yes"
image: neo4j
imageTag: 3.5.5-enterprise
imagePullPolicy: IfNotPresent
authEnabled: false
metrics:
  prometheus:
    enabled: true
    endpoint: localhost:2004    
core:
  extraVars:
  - name: NEO4J_dbms_security_procedures_whitelist
    value: "apoc.*"
  - name: NEO4J_metrics_prometheus_enabled
    value: "true"
  - name: NEO4J_metrics_prometheus_endpoint
    value: "localhost:2004"
  persistentVolume:
    size: 1Gi
  initContainers:
  - name: init-plugins
    image: "appropriate/curl:latest"
    imagePullPolicy: "IfNotPresent"
    volumeMounts:
    - name: plugins
      mountPath: /plugins
    command:
      - "/bin/sh"
      - "-c"
      - |
        curl -L https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.5.0.3/apoc-3.5.0.3-all.jar -O &&
        cp apoc-3.5.0.3-all.jar /plugins/ &&
        curl -L https://github.com/neo4j-graphql/neo4j-graphql/releases/download/3.4.0.1/neo4j-graphql-3.4.0.1.jar -O &&
        cp neo4j-graphql-3.4.0.1.jar /plugins/
  - name: init-data
    image: "conference-data:1"
    imagePullPolicy: "IfNotPresent"
    volumeMounts:
    - name: datadir
      mountPath: /data
    command:
      - "bin/sh"
      - "-c" 
      - |
        cp -r /tmp/graph.db/ /data/databases/

