apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo
  labels:
    app: apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo
  template:
    metadata:
      labels:
        app: apollo
    spec:
      containers:
      - name: apollo
        image: conference-api:1 
        envFrom:    
        - configMapRef:
            name: apollo-config
        ports:
        - containerPort: 4000
