query Flyer {
  Location {
    name
    state
    city
    rooms {
      id
      name
      size
      description
      allocations(orderBy: startDateTime_asc) {
        startDateTime
        endDateTime
        talk {
          name
          topics {
            name
          }
        }
        speaker {
          firstName
          lastName
          company
        }
      }
    }
  }
}
